version: "3.8"

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.cong:/etc/nginx/nginx.conf:ro
  # php:
  # mysql:
  # composer:
  # artisan:
  # npm:
